//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleStatisticsComsumer.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.webserviceX.NET", ConfigurationName="ServiceReference1.StatisticsSoap")]
    public interface StatisticsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetStatistics", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SimpleStatisticsComsumer.ServiceReference1.GetStatisticsResponse GetStatistics(SimpleStatisticsComsumer.ServiceReference1.GetStatisticsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetStatistics", ReplyAction="*")]
        System.Threading.Tasks.Task<SimpleStatisticsComsumer.ServiceReference1.GetStatisticsResponse> GetStatisticsAsync(SimpleStatisticsComsumer.ServiceReference1.GetStatisticsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStatistics", WrapperNamespace="http://www.webserviceX.NET", IsWrapped=true)]
    public partial class GetStatisticsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.webserviceX.NET", Order=0)]
        public double[] X;
        
        public GetStatisticsRequest() {
        }
        
        public GetStatisticsRequest(double[] X) {
            this.X = X;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStatisticsResponse", WrapperNamespace="http://www.webserviceX.NET", IsWrapped=true)]
    public partial class GetStatisticsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.webserviceX.NET", Order=0)]
        public double Sums;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.webserviceX.NET", Order=1)]
        public double Average;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.webserviceX.NET", Order=2)]
        public double StandardDeviation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.webserviceX.NET", Order=3)]
        public double skewness;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.webserviceX.NET", Order=4)]
        public double Kurtosis;
        
        public GetStatisticsResponse() {
        }
        
        public GetStatisticsResponse(double Sums, double Average, double StandardDeviation, double skewness, double Kurtosis) {
            this.Sums = Sums;
            this.Average = Average;
            this.StandardDeviation = StandardDeviation;
            this.skewness = skewness;
            this.Kurtosis = Kurtosis;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StatisticsSoapChannel : SimpleStatisticsComsumer.ServiceReference1.StatisticsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StatisticsSoapClient : System.ServiceModel.ClientBase<SimpleStatisticsComsumer.ServiceReference1.StatisticsSoap>, SimpleStatisticsComsumer.ServiceReference1.StatisticsSoap {
        
        public StatisticsSoapClient() {
        }
        
        public StatisticsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StatisticsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatisticsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatisticsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimpleStatisticsComsumer.ServiceReference1.GetStatisticsResponse SimpleStatisticsComsumer.ServiceReference1.StatisticsSoap.GetStatistics(SimpleStatisticsComsumer.ServiceReference1.GetStatisticsRequest request) {
            return base.Channel.GetStatistics(request);
        }
        
        public double GetStatistics(double[] X, out double Average, out double StandardDeviation, out double skewness, out double Kurtosis) {
            SimpleStatisticsComsumer.ServiceReference1.GetStatisticsRequest inValue = new SimpleStatisticsComsumer.ServiceReference1.GetStatisticsRequest();
            inValue.X = X;
            SimpleStatisticsComsumer.ServiceReference1.GetStatisticsResponse retVal = ((SimpleStatisticsComsumer.ServiceReference1.StatisticsSoap)(this)).GetStatistics(inValue);
            Average = retVal.Average;
            StandardDeviation = retVal.StandardDeviation;
            skewness = retVal.skewness;
            Kurtosis = retVal.Kurtosis;
            return retVal.Sums;
        }
        
        public System.Threading.Tasks.Task<SimpleStatisticsComsumer.ServiceReference1.GetStatisticsResponse> GetStatisticsAsync(SimpleStatisticsComsumer.ServiceReference1.GetStatisticsRequest request) {
            return base.Channel.GetStatisticsAsync(request);
        }
    }
}
